name: Push actions

on:
  push:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project and test requirements
        run: python -m pip install -e . -r requirements_test.txt

      - name: Run tests
        run: |
          python -m pytest \
            -vv \
            -qq \
            --timeout=9 \
            --durations=10 \
            --cov podpointclient \
            --cov-report term \
            --cov-report html \
            -o console_output_style=count \
            -p no:sugar \
            tests

      - name: Store code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: htmlcov/
          if-no-files-found: error
